comida_cumpleaños = ["mama", "papa", "raquel", "ceci"]
comida_cumpleaños[0]=("abuela")
comida_cumpleaños[1]=("pita")
comida_cumpleaños[2]=("padrino")
comida_cumpleaños[3]=("madrina")
comida_cumpleaños.insert(0, "tio manolo")
comida_cumpleaños.insert(-1, "sofia")
comida_cumpleaños.append("tia viqui")
print(f"Hola, {comida_cumpleaños[0].title()} quería informarte de que haré mi comida de cumpleaños el dia 16 en Valilongo")
print(f"Hola, {comida_cumpleaños[1].title()} quería informarte de que haré mi comida de cumpleaños el dia 16 en Valilongo")
print(f"Hola, {comida_cumpleaños[2].title()} quería informarte de que haré mi comida de cumpleaños el dia 16 en Valilongo")
print(f"Hola, {comida_cumpleaños[3].title()} quería informarte de que haré mi comida de cumpleaños el dia 16 en Valilongo")
print(f"Hola, {comida_cumpleaños[4].title()} quería informarte de que haré mi comida de cumpleaños el dia 16 en Valilongo")
print(f"Hola, {comida_cumpleaños[5].title()} quería informarte de que haré mi comida de cumpleaños el dia 16 en Valilongo")
print(f"Hola, {comida_cumpleaños[6].title()} quería informarte de que haré mi comida de cumpleaños el dia 16 en Valilongo")
print(f"Hola{comida_cumpleaños} siento comunicaros que solo podré invitar a dos personas debido a problemas con la mesa, disculpad las molestias")