comida_cumpleaños = ["mama", "papa", "raquel", "ceci"]
comida_cumpleaños[0]=("abuela")
comida_cumpleaños[1]=("pita")
comida_cumpleaños[2]=("padrino")
comida_cumpleaños[3]=("madrina")
comida_cumpleaños.insert(0, "tio manolo")
comida_cumpleaños.insert(-1, "sofia")
comida_cumpleaños.append("tia viqui")
print(comida_cumpleaños)
pop_1=comida_cumpleaños.pop(0)
print(f"Hola {pop_1.title()} siento comunicarte que no podre invitarte a comer")
pop_2=comida_cumpleaños.pop(0)
print(f"Hola {pop_2.title()} siento comunicarte que no podré invitarte a mi cumpleaños")
pop_3=comida_cumpleaños.pop(0)
print(f"Hola {pop_3.title()} siento comunicarte que no puedo invitarte a mi cumpleaños")
pop_4=comida_cumpleaños.pop(0)
print(f"Hola {pop_4.title()} siento comunicarte que no puedo invitarte a mi cumpleaños")
pop_5=comida_cumpleaños.pop(0)
print(f"Hola {pop_5.title()} siento comunicarte que no puedo invitarte a mi cumpleaños")
print(f"Hola {comida_cumpleaños[0].title()} cuento contigo para el día 16, nos vemos en Valilongo")
print(f"Hola {comida_cumpleaños[1].title()} cuento contigo para el día 16, nos vemos en Valilongo")
del comida_cumpleaños[0]
del comida_cumpleaños[0]
print(comida_cumpleaños)